#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Convert THUMOS14-TAD-GCD split json to OpenTAD-compatible annotation files.

Input:
    A json generated by:
        tad_gcd/datasets/build_thumos14_tad_gcd_index.py

Output:
    data/thumos14_tad_gcd/opentad/
    ├── thumos14_tad_gcd_train_labeled.json
    ├── thumos14_tad_gcd_train_unlabeled.json
    ├── thumos14_tad_gcd_test.json
    ├── thumos14_tad_gcd_test_old.json
    ├── thumos14_tad_gcd_test_new.json
    ├── category_idx_old.txt
    ├── category_idx_new.txt
    ├── category_idx_all.txt
    └── class_split.json

Important OpenTAD convention:
    configs/_base_/datasets/thumos-14/features_i3d_pad.py uses:
        train subset_name = "training"
        val/test subset_name = "validation"

Therefore:
    train_labeled   -> subset = "training"
    train_unlabeled -> subset = "training"
    test            -> subset = "validation"
    test_old        -> subset = "validation"
    test_new        -> subset = "validation"

Training restriction:
    OpenTAD old-class detector should only use:
        thumos14_tad_gcd_train_labeled.json
        thumos14_tad_gcd_test_old.json
        category_idx_old.txt

    It must not use:
        test_new labels
        new class names
        new_label_to_eval_id
        hidden new summary
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


OPEN_TAD_SPLIT_JOBS = [
    ("train_labeled", "training", "thumos14_tad_gcd_train_labeled.json"),
    ("train_unlabeled", "training", "thumos14_tad_gcd_train_unlabeled.json"),
    ("test", "validation", "thumos14_tad_gcd_test.json"),
    ("test_old", "validation", "thumos14_tad_gcd_test_old.json"),
    ("test_new", "validation", "thumos14_tad_gcd_test_new.json"),
]


def load_json(path: str) -> Dict[str, Any]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Input json does not exist: {p}")

    with open(p, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        raise ValueError(f"Expected dict json at {p}, got {type(data)}")

    return data


def write_json(obj: Dict[str, Any], path: Path, indent: int = 2) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=indent, ensure_ascii=False)


def write_lines(lines: Iterable[str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    clean = [str(x).strip() for x in lines if str(x).strip()]
    path.write_text("\n".join(clean) + "\n", encoding="utf-8")


def as_float_or_none(x: Any) -> Optional[float]:
    if x is None:
        return None
    try:
        return float(x)
    except Exception:
        return None


def as_int_or_none(x: Any) -> Optional[int]:
    if x is None:
        return None
    try:
        return int(round(float(x)))
    except Exception:
        return None


def normalize_video_id(video_id: Any) -> str:
    return str(video_id).strip()


def get_video_id_variants(video_id: str) -> List[str]:
    """
    Some THUMOS annotations or feature files may use slightly different keys.
    This function gives a few safe variants for matching reference metadata.
    """
    vid = normalize_video_id(video_id)
    variants = [vid]

    # Remove common file suffixes if any were accidentally included.
    for suffix in [".mp4", ".avi", ".mkv", ".webm", ".npy"]:
        if vid.endswith(suffix):
            variants.append(vid[: -len(suffix)])

    # Add common THUMOS naming variants.
    if vid.startswith("video_"):
        variants.append(vid[len("video_") :])
    else:
        variants.append("video_" + vid)

    # De-duplicate while preserving order.
    out = []
    seen = set()
    for v in variants:
        if v and v not in seen:
            out.append(v)
            seen.add(v)
    return out


def build_reference_meta(reference_json: Optional[str]) -> Dict[str, Dict[str, Any]]:
    """
    Optional helper:
    If TAD-GCD split json does not contain duration/frame, load an OpenTAD
    original THUMOS annotation json and use it to fill duration/frame/fps.

    Expected reference format:
        {
          "database": {
            "video_validation_0000051": {
              "subset": "validation",
              "duration": ...,
              "frame": ...,
              "fps": ...,
              "annotations": [...]
            }
          }
        }

    The function is permissive and only extracts duration/frame/fps.
    """
    if reference_json is None:
        return {}

    path = Path(reference_json)
    if not path.exists():
        raise FileNotFoundError(f"Reference annotation json does not exist: {path}")

    raw = load_json(str(path))
    database = raw.get("database", raw)
    if not isinstance(database, dict):
        raise ValueError(f"Unsupported reference json format: {path}")

    meta: Dict[str, Dict[str, Any]] = {}

    for raw_vid, info in database.items():
        if not isinstance(info, dict):
            continue

        vid = normalize_video_id(raw_vid)
        entry = {}

        for key in ["duration", "frame", "fps"]:
            if key in info and info[key] is not None:
                entry[key] = info[key]

        if not entry:
            continue

        for v in get_video_id_variants(vid):
            meta[v] = entry

    return meta


def fill_duration_frame_fps(
    item: Dict[str, Any],
    reference_meta: Dict[str, Dict[str, Any]],
    default_fps: Optional[float],
) -> Dict[str, Any]:
    """
    OpenTAD THUMOS dataset needs at least duration and frame.

    Priority:
        1. Use fields already in TAD-GCD item.
        2. Use reference_meta by video_id.
        3. If duration exists and default_fps is provided, infer frame.
        4. If frame and duration exist but fps missing, infer fps.
    """
    video_id = normalize_video_id(item.get("video_id", ""))

    duration = item.get("duration", None)
    frame = item.get("frame", None)
    fps = item.get("fps", None)

    ref = None
    for v in get_video_id_variants(video_id):
        if v in reference_meta:
            ref = reference_meta[v]
            break

    if ref is not None:
        if duration is None and ref.get("duration", None) is not None:
            duration = ref["duration"]
        if frame is None and ref.get("frame", None) is not None:
            frame = ref["frame"]
        if fps is None and ref.get("fps", None) is not None:
            fps = ref["fps"]

    duration_f = as_float_or_none(duration)
    frame_i = as_int_or_none(frame)
    fps_f = as_float_or_none(fps)

    if frame_i is None and duration_f is not None and default_fps is not None:
        frame_i = int(round(duration_f * float(default_fps)))

    if fps_f is None and duration_f is not None and frame_i is not None and duration_f > 0:
        fps_f = float(frame_i) / float(duration_f)

    out = dict(item)
    if duration_f is not None:
        out["duration"] = duration_f
    if frame_i is not None:
        out["frame"] = frame_i
    if fps_f is not None:
        out["fps"] = fps_f

    return out


def convert_annotation(ann: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Convert TAD-GCD annotation:
        {"start": ..., "end": ..., "label": ...}

    To OpenTAD style:
        {"segment": [start, end], "label": ...}

    New-class fields such as eval_id are intentionally not copied.
    """
    if not isinstance(ann, dict):
        return None

    if "start" not in ann or "end" not in ann or "label" not in ann:
        return None

    start = as_float_or_none(ann["start"])
    end = as_float_or_none(ann["end"])
    label = str(ann["label"]).strip()

    if start is None or end is None or not label:
        return None

    if end <= start:
        return None

    return {
        "segment": [float(start), float(end)],
        "label": label,
    }


def convert_item(
    item: Dict[str, Any],
    opentad_subset_name: str,
    reference_meta: Dict[str, Dict[str, Any]],
    default_fps: Optional[float],
    require_duration_frame: bool,
) -> Tuple[str, Dict[str, Any]]:
    if "video_id" not in item:
        raise ValueError(f"Item missing video_id: {item}")

    item = fill_duration_frame_fps(
        item=item,
        reference_meta=reference_meta,
        default_fps=default_fps,
    )

    video_id = normalize_video_id(item["video_id"])

    out: Dict[str, Any] = {
        "subset": opentad_subset_name,
        "annotations": [],
    }

    if "duration" in item and item["duration"] is not None:
        out["duration"] = float(item["duration"])

    if "frame" in item and item["frame"] is not None:
        out["frame"] = int(item["frame"])

    if "fps" in item and item["fps"] is not None:
        out["fps"] = float(item["fps"])

    # Keep path information as metadata. OpenTAD normally uses data_path rather
    # than per-video feat_path, but keeping it here helps debugging and later
    # proposal feature extraction.
    if "video_path" in item and item["video_path"] is not None:
        out["video_path"] = item["video_path"]

    if "feat_path" in item and item["feat_path"] is not None:
        out["feat_path"] = item["feat_path"]

    for ann in item.get("annotations", []):
        converted = convert_annotation(ann)
        if converted is not None:
            out["annotations"].append(converted)

    out["annotations"] = sorted(
        out["annotations"],
        key=lambda x: (x["segment"][0], x["segment"][1], x["label"]),
    )

    if require_duration_frame:
        missing = []
        if "duration" not in out:
            missing.append("duration")
        if "frame" not in out:
            missing.append("frame")
        if missing:
            raise RuntimeError(
                f"Video {video_id} is missing required OpenTAD fields: {missing}. "
                "OpenTAD THUMOS dataset needs duration and frame. "
                "Use --reference_opentad_ann to fill these fields from the original "
                "OpenTAD annotation json, or use --default_fps if duration exists."
            )

    return video_id, out


def convert_split(
    data: Dict[str, Any],
    split_key: str,
    opentad_subset_name: str,
    reference_meta: Dict[str, Dict[str, Any]],
    default_fps: Optional[float],
    require_duration_frame: bool,
) -> Dict[str, Any]:
    entries = data.get(split_key, [])
    if not isinstance(entries, list):
        raise ValueError(f"Expected list for split {split_key}, got {type(entries)}")

    database: Dict[str, Any] = {}

    for item in entries:
        if not isinstance(item, dict):
            continue

        video_id, value = convert_item(
            item=item,
            opentad_subset_name=opentad_subset_name,
            reference_meta=reference_meta,
            default_fps=default_fps,
            require_duration_frame=require_duration_frame,
        )
        database[video_id] = value

    return {
        "version": "THUMOS14-TAD-GCD for OpenTAD",
        "database": database,
    }


def collect_labels_from_opentad_json(opentad_data: Dict[str, Any]) -> List[str]:
    labels = set()
    database = opentad_data.get("database", {})
    for info in database.values():
        if not isinstance(info, dict):
            continue
        for ann in info.get("annotations", []):
            if isinstance(ann, dict) and "label" in ann:
                labels.add(str(ann["label"]))
    return sorted(labels)


def count_instances(opentad_data: Dict[str, Any]) -> int:
    database = opentad_data.get("database", {})
    return sum(
        len(info.get("annotations", []))
        for info in database.values()
        if isinstance(info, dict)
    )


def count_missing_field(opentad_data: Dict[str, Any], key: str) -> int:
    database = opentad_data.get("database", {})
    return sum(
        1
        for info in database.values()
        if isinstance(info, dict) and key not in info
    )


def collect_subsets(opentad_data: Dict[str, Any]) -> List[str]:
    database = opentad_data.get("database", {})
    return sorted(
        {
            str(info.get("subset", ""))
            for info in database.values()
            if isinstance(info, dict)
        }
    )


def validate_input_tad_gcd(data: Dict[str, Any]) -> None:
    required_keys = [
        "class_split",
        "label_mapping",
        "train_labeled",
        "train_unlabeled",
        "test",
        "test_old",
        "test_new",
    ]
    missing = [k for k in required_keys if k not in data]
    if missing:
        raise KeyError(f"Input TAD-GCD json missing required keys: {missing}")

    class_split = data["class_split"]
    if "old_classes" not in class_split or "new_classes" not in class_split:
        raise KeyError("class_split must contain old_classes and new_classes.")

    old_classes = set(class_split["old_classes"])
    new_classes = set(class_split["new_classes"])

    overlap = sorted(old_classes & new_classes)
    if overlap:
        raise RuntimeError(f"old_classes and new_classes overlap: {overlap}")

    # Check training leakage in the original TAD-GCD json before conversion.
    leaked = []
    for item in data.get("train_labeled", []):
        for ann in item.get("annotations", []):
            label = ann.get("label")
            if label in new_classes or ann.get("class_type") == "new" or "eval_id" in ann:
                leaked.append((item.get("video_id"), ann))

    if leaked:
        raise RuntimeError(
            "New-class leakage detected in train_labeled before conversion. "
            f"First leaked annotation: {leaked[0]}"
        )

    bad_unlabeled = []
    for item in data.get("train_unlabeled", []):
        if item.get("annotations", []) != []:
            bad_unlabeled.append(item.get("video_id"))

    if bad_unlabeled:
        raise RuntimeError(
            "train_unlabeled must have empty annotations before conversion. "
            f"First bad video: {bad_unlabeled[0]}"
        )


def validate_outputs(
    converted: Dict[str, Dict[str, Any]],
    old_classes: List[str],
    new_classes: List[str],
    require_duration_frame: bool,
) -> None:
    old_set = set(old_classes)
    new_set = set(new_classes)

    train_labels = set(collect_labels_from_opentad_json(converted["train_labeled"]))
    train_unlabeled_labels = set(collect_labels_from_opentad_json(converted["train_unlabeled"]))
    test_labels = set(collect_labels_from_opentad_json(converted["test"]))
    test_old_labels = set(collect_labels_from_opentad_json(converted["test_old"]))
    test_new_labels = set(collect_labels_from_opentad_json(converted["test_new"]))

    if not train_labels <= old_set:
        raise RuntimeError(f"train_labeled contains non-old labels: {sorted(train_labels - old_set)}")

    if train_unlabeled_labels:
        raise RuntimeError(f"train_unlabeled must not contain labels: {sorted(train_unlabeled_labels)}")

    if not test_old_labels <= old_set:
        raise RuntimeError(f"test_old contains non-old labels: {sorted(test_old_labels - old_set)}")

    if not test_new_labels <= new_set:
        raise RuntimeError(f"test_new contains non-new labels: {sorted(test_new_labels - new_set)}")

    if not test_labels <= (old_set | new_set):
        raise RuntimeError(f"test contains labels outside old/new split: {sorted(test_labels - old_set - new_set)}")

    expected_subsets = {
        "train_labeled": ["training"],
        "train_unlabeled": ["training"],
        "test": ["validation"],
        "test_old": ["validation"],
        "test_new": ["validation"],
    }

    for split_key, expected in expected_subsets.items():
        got = collect_subsets(converted[split_key])
        if got != expected:
            raise RuntimeError(
                f"{split_key} has wrong OpenTAD subset names. "
                f"Expected {expected}, got {got}"
            )

    if require_duration_frame:
        for split_key, out in converted.items():
            missing_duration = count_missing_field(out, "duration")
            missing_frame = count_missing_field(out, "frame")
            if missing_duration or missing_frame:
                raise RuntimeError(
                    f"{split_key} still has missing OpenTAD fields: "
                    f"missing_duration={missing_duration}, missing_frame={missing_frame}"
                )


def write_class_maps(data: Dict[str, Any], output_dir: Path) -> None:
    old_classes = data["class_split"]["old_classes"]
    new_classes = data["class_split"]["new_classes"]

    write_lines(old_classes, output_dir / "category_idx_old.txt")
    write_lines(new_classes, output_dir / "category_idx_new.txt")
    write_lines(old_classes + new_classes, output_dir / "category_idx_all.txt")


def write_class_split_meta(data: Dict[str, Any], output_dir: Path, input_path: str) -> None:
    meta = {
        "class_split": data["class_split"],
        "label_mapping": data.get("label_mapping", {}),
        "split_config": data.get("split_config", {}),
        "source": str(input_path),
        "training_usage": {
            "old_detector_train_annotation": "thumos14_tad_gcd_train_labeled.json",
            "old_detector_eval_annotation": "thumos14_tad_gcd_test_old.json",
            "old_detector_class_map": "category_idx_old.txt",
        },
        "forbidden_in_training": [
            "thumos14_tad_gcd_test_new.json",
            "category_idx_new.txt",
            "new_label_to_eval_id",
            "train_hidden_new_summary",
        ],
    }
    write_json(meta, output_dir / "class_split.json")


def print_summary(split_name: str, output_path: Path, out: Dict[str, Any]) -> None:
    labels = collect_labels_from_opentad_json(out)
    subsets = collect_subsets(out)
    n_videos = len(out.get("database", {}))
    n_instances = count_instances(out)
    missing_duration = count_missing_field(out, "duration")
    missing_frame = count_missing_field(out, "frame")

    print("=" * 80)
    print(f"{split_name} -> {output_path}")
    print(f"videos           : {n_videos}")
    print(f"instances        : {n_instances}")
    print(f"subsets          : {subsets}")
    print(f"labels({len(labels)})       : {labels}")
    print(f"missing_duration : {missing_duration}")
    print(f"missing_frame    : {missing_frame}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert THUMOS14-TAD-GCD split json to OpenTAD-compatible annotation jsons."
    )

    parser.add_argument(
        "--input",
        required=True,
        type=str,
        help="Input json generated by tad_gcd/datasets/build_thumos14_tad_gcd_index.py.",
    )
    parser.add_argument(
        "--output_dir",
        default="data/thumos14_tad_gcd/opentad",
        type=str,
        help="Directory to save OpenTAD-format annotation files.",
    )
    parser.add_argument(
        "--reference_opentad_ann",
        default=None,
        type=str,
        help=(
            "Optional original OpenTAD THUMOS annotation json. "
            "Used to fill duration/frame/fps if missing in TAD-GCD json."
        ),
    )
    parser.add_argument(
        "--default_fps",
        default=None,
        type=float,
        help=(
            "Optional FPS used to infer frame = round(duration * fps) "
            "when frame is missing but duration exists."
        ),
    )
    parser.add_argument(
        "--allow_missing_duration_frame",
        action="store_true",
        help=(
            "Allow converted json to miss duration/frame. "
            "Not recommended for OpenTAD THUMOS training."
        ),
    )
    parser.add_argument(
        "--indent",
        default=2,
        type=int,
        help="JSON indentation.",
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    require_duration_frame = not args.allow_missing_duration_frame

    data = load_json(str(input_path))
    validate_input_tad_gcd(data)

    old_classes = data["class_split"]["old_classes"]
    new_classes = data["class_split"]["new_classes"]

    reference_meta = build_reference_meta(args.reference_opentad_ann)

    converted: Dict[str, Dict[str, Any]] = {}
    output_paths: Dict[str, Path] = {}

    for split_key, opentad_subset_name, filename in OPEN_TAD_SPLIT_JOBS:
        out = convert_split(
            data=data,
            split_key=split_key,
            opentad_subset_name=opentad_subset_name,
            reference_meta=reference_meta,
            default_fps=args.default_fps,
            require_duration_frame=require_duration_frame,
        )

        converted[split_key] = out
        output_paths[split_key] = output_dir / filename

    validate_outputs(
        converted=converted,
        old_classes=old_classes,
        new_classes=new_classes,
        require_duration_frame=require_duration_frame,
    )

    for split_key, _, _ in OPEN_TAD_SPLIT_JOBS:
        write_json(converted[split_key], output_paths[split_key], indent=args.indent)
        print_summary(split_key, output_paths[split_key], converted[split_key])

    write_class_maps(data, output_dir)
    write_class_split_meta(data, output_dir, str(input_path))

    print("=" * 80)
    print(f"Saved class maps and class split meta to: {output_dir}")
    print("-" * 80)
    print("Generated files:")
    for _, _, filename in OPEN_TAD_SPLIT_JOBS:
        print(f"  {output_dir / filename}")
    print(f"  {output_dir / 'category_idx_old.txt'}")
    print(f"  {output_dir / 'category_idx_new.txt'}")
    print(f"  {output_dir / 'category_idx_all.txt'}")
    print(f"  {output_dir / 'class_split.json'}")
    print("=" * 80)
    print("Conversion finished successfully.")
    print("=" * 80)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print("=" * 80, file=sys.stderr)
        print("convert_tad_gcd_to_opentad.py failed.", file=sys.stderr)
        print(str(exc), file=sys.stderr)
        print("=" * 80, file=sys.stderr)
        raise